site_name: PDC
theme: 
  name: material
  font:
    text: 'Roboto'
    code: 'Fira Code'
extra_css:
  - static/css/styles.css
extra_javascript:
  - static/js/custom.js
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - attr_list
nav:
  - Home: index.md
  - Site Map: site_map.md
  - Quick start guide: 
    - Quick Start: basics/quickstart.md
  - Introduction: 
    - Introduction: basics/introduction.md
  - Requesting resources: 
    - Getting Access: getting_access/get_access.md
  - How to Login: 
    - How to log in with SSH keys: login/ssh_login.md
    - Generating SSH keys: login/ssh_keys.md
    - How to log in with kerberos: login/kerberos_login.md
    - How to login from Linux: login/linux_login.md
    - How to login from Windows: login/windows_login.md
    - How to login from Mac OS: login/mac_login.md
    - How to configure kerberos and SSH: login/configuration.md 
    - How to reset your password: login/reset_password.md
    - Interactive HPC at PDC: login/interactive_hpc.md
  - How to Run Jobs: 
    - How to Run Jobs: run_jobs/job_scheduling.md
    - How to submit jobs: run_jobs/queueing_jobs.md
    - Job scripts: run_jobs/job_scripts.md
    - Job script examples: run_jobs/job_scripts_dardel.md
    - Job arrays: run_jobs/job_arrays.md
    - Short jobs: run_jobs/short_jobs.md
    - Run interactively: run_jobs/run_interactively.md
    - Job Statistics: run_jobs/job_statistics.md
  - Available Software: 
    - How to get information about installed softwares: software/software.md
    - How to use module to load different softwares into your environment: software/module.md
  - Data Management: 
    - Data Management: data_management/data_management.md
    - Klemming: data_management/klemming.md
    - Swestore: data_management/file_transfer_swestore-dcache.md
    - File transfer: data_management/file_transfer_scp.md
    - KTH OneDrive(rclone): data_management/rclone_onedrive.md
  - Software Development: 
    - Compilers and libraries: software_development/development.md
    - Building for AMD GPUs: software_development/development_gpu.md
    - Allinea Forge: software_development/development_allineaforge.md
    - Downloadable example for compiling and submitting: software_development/development_example.md
    - References: software_development/development_references.md
    - Installing software using EasyBuild: software_development/easybuild.md
    - Installing software using Spack: software_development/spack.md
  - Industry: 
    - Practical information for industry projects: industry/industry.md
    - SCANIA: industry/scania.md
  - Courses: 
    - General instructions for PDC courses: courses/general.md
    - PRACE deep learning: courses/deeplearning.md
    - Introduction to PDC: courses/pdcintro.md
    - PDC summer school: courses/summerschool.md
    - PDC/PRACE workshop HPC Tools for the Modern Era: courses/prace.md
  - PDC Blog: 
    - PDC Blog: https://www.kth.se/blogs/pdc
  - Frequently Asked Questions  FAQ: 
    - Frequently Asked Questions (FAQ): faq/faq.md
  - Contact Support: 
    - Contact Support: contact/contact_support.md
